name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-dev   

    - name: configure
      run: cd sdcc; ./configure --disable-pic14-port --disable-pic16-port
      
    - name: make
      run: cd sdcc; make -j 2
      
    - name: Run check
      run: cd sdcc/support/regression; make test-uc6502
           
