name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    name: Test on  ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]


    steps:
    - uses: actions/checkout@v2
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-dev   

    - name: configure
      run: cd sdcc; ./configure --disable-pic14-port --disable-pic16-port
      
    - name: make
      run: cd sdcc; make -j 2
      
    - name: test 6502 port
      run: cd sdcc/support/regression; make test-uc6502 -j 2

    - name: test STM8 port
      run: cd sdcc/support/regression; make test-stm8 -j 2

    - name: test S08 port
      run: cd sdcc/support/regression; make test-s08 -j 2

    - name: test Z80 port
      run: cd sdcc/support/regression; make test-ucz80 -j 2

